module MobilityConstant
  # version 1.0 unless defined? 
  TIMESTAMP="timestamp" unless defined? TIMESTAMP
  CLIENT="client_mac" unless defined? CLIENT
  NAMESPACE="namespace" unless defined? NAMESPACE
  CAMPUS="campus" unless defined? CAMPUS
  BUILDING="building" unless defined? BUILDING
  FLOOR="floor" unless defined? FLOOR
  ZONE="zone" unless defined? ZONE
  T_GLOBAL_LAST_SEEN="t_global_last_seen" unless defined? T_GLOBAL_LAST_SEEN
  T_GLOBAL="t_global" unless defined? T_GLOBAL
  T_LAST_SEEN="t_last_seen" unless defined? T_LAST_SEEN
  T_TRANSITION="t_transition" unless defined? T_TRANSITION
  DWELL_TIME="dwell_time" unless defined? DWELL_TIME
  SESSION="session" unless defined? SESSION
  TRANSITION="transition" unless defined? TRANSITION
  NEW_LOC="new" unless defined? NEW_LOC
  OLD_LOC="old" unless defined? OLD_LOC
  CONSOLIDATED="consolidated" unless defined? CONSOLIDATED
  ENTRANCE="entrance" unless defined? ENTRANCE
  TYPE="type" unless defined? TYPE
  REPEAT_LOCATION="repeat_location" unless defined? REPEAT_LOCATION
  REPETITIONS="repetitions" unless defined? REPETITIONS
  POPULARITY="popularity" unless defined? POPULARITY
  MINUTE=60 unless defined? MINUTE
  UUID="uuid" unless defined? UUID
  ZONE_UUID="zone_uuid" unless defined? ZONE_UUID
  SERVICE_PROVIDER_UUID="service_provider_uuid" unless defined? SERVICE_PROVIDER_UUID
  BUILDING_UUID="building_uuid" unless defined? BUILDING_UUID
  CAMPUS_UUID="campus_uuid" unless defined? CAMPUS_UUID
  FLOOR_UUID="floor_uuid" unless defined? FLOOR_UUID
  DEPLOYMENT_UUID="deployment_uuid" unless defined? DEPLOYMENT_UUID
  NAMESPACE_UUID="namespace_uuid" unless defined? NAMESPACE_UUID
  SENSOR_UUID="sensor_uuid" unless defined? SENSOR_UUID
  MARKET_UUID="market_uuid" unless defined? MARKET_UUID
  ORGANIZATION_UUID="organization_uuid" unless defined? ORGANIZATION_UUID
  LATLONG="client_latlong" unless defined? LATLONG
  # Extra unless defined? 
  STATUS="dot11_status" unless defined? STATUS
  CLIENT_PROFILE="client_profile" unless defined? CLIENT_PROFILE
  CLIENT_RSSI_NUM="client_rssi_num" unless defined? CLIENT_RSSI_NUM
end
