# version 1.0
TIMESTAMP="timestamp"
CLIENT="client_mac"
NAMESPACE="namespace"
CAMPUS="campus"
BUILDING="building"
FLOOR="floor"
ZONE="zone"

T_GLOBAL_LAST_SEEN="t_global_last_seen"

T_GLOBAL="t_global"
T_LAST_SEEN="t_last_seen"
T_TRANSITION="t_transition"
DWELL_TIME="dwell_time"
SESSION="session"
TRANSITION="transition"
NEW_LOC="new"
OLD_LOC="old"
CONSOLIDATED="consolidated"
ENTRANCE="entrance"
TYPE="type"
REPEAT_LOCATION="repeat_location"
REPETITIONS="repetitions"
POPULARITY="popularity"

MINUTE=60
UUID="uuid"

ZONE_UUID="zone_uuid"
SERVICE_PROVIDER_UUID="service_provider_uuid"
BUILDING_UUID="building_uuid"
CAMPUS_UUID="campus_uuid"
FLOOR_UUID="floor_uuid"
DEPLOYMENT_UUID="deployment_uuid"
NAMESPACE_UUID="namespace_uuid"
SENSOR_UUID="sensor_uuid"
MARKET_UUID="market_uuid"
ORGANIZATION_UUID="organization_uuid"
LATLONG="client_latlong"

# Extra
STATUS="dot11_status"
CLIENT_PROFILE="client_profile"
CLIENT_RSSI_NUM="client_rssi_num"
